Repository BesLyric-for-X/BesLyric-for-X, pull requests merged in 2021-02, with the labels that each got.

#122 设置应用名称以使数据文件路径不变
  main.cpp
Labels: bug

#123 ! 新的依赖指令 2
  Beslyric-for-X.pro
  Entities/MP3Editor/ffmpegDefine.h
  Entities/MusicPlayer/musicPlayer.h
Labels: _Lib files on win32

#119 在登陆统计时，新增系统架构信息的收集
  Entities/ThreadLogin.h
Labels: enhancement

#121 输出的时间标签格式由3位小数位调整为2位小数位
  Entities/LyricMaker.cpp
Labels: enhancement

#124 不在 Qt 5.12 及更低版本中使用未引入的 QUrlQuery 的列表初始化构造方法
  Entities/ThreadLogin.h
Labels: bug

#125 使用一个校准后的新图标替换一个旧图标，并移除另一个没用的旧图标
  BesLyric.icns
  Beslyric.ico
  MiddleWidgets/BoxPageLyricList.cpp
  StackFrame.cpp
  TopWidgets/TopWidget.cpp
  resource.qrc
  resource/image/netease_cloudmusic_32px.ico
  resource/image/netease_cloudmusic_48px.ico
Labels: _UI-appearance

#126 Revert "在 Shadow build 禁用时阻止构建以避免输出文件被覆盖"
  Beslyric-for-X.pro
Labels: bug

#127 程序启动时输出用于构建当前程序的源代码的 Git 提交 SHA1
  Beslyric-for-X.pro
  MiddleWidgets/SettingWidget/SuUpgrade.cpp
  MiddleWidgets/SettingWidget/SuUpgrade.h
  StackFrame.cpp
  StackFrame.h
Labels: enhancement

#128 为避免硬编码版本号，将其由外界传入，并使用 qmake 自动生成相关字段
  BesLyric.rc
  Beslyric-for-X.pro
  Define/Static.h
Labels: enhancement

#129 在定义了 RELEASE_VERSION 时，定义 QT_NO_DEBUG_OUTPUT 以禁用 qDebug
  Beslyric-for-X.pro
Labels: enhancement
